# upload website to s3 bucket

name: uploadToS3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Sync files to S3
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}; \
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        aws s3 sync website/pages s3://${{ secrets.AWS_S3_BUCKET }}/pages \
          --endpoint-url ${{ secrets.AWS_ENDPOINT_URL }} \
          --region ${{ secrets.AWS_REGION_NAME }} \
          --delete; \
        unset AWS_ACCESS_KEY_ID;
        unset AWS_SECRET_ACCESS_KEY;
