# upload website to s3 bucket

name: uploadToS3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Sync files to S3
      # direct exclude with globing does not work properly, so using enumeration of subdirs
      # "when_required" - aws bug https://github.com/aws/aws-cli/issues/9214
      env:
        AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REQUEST_CHECKSUM_CALCULATION: when_required
        AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
        AG_GRID_CDN_URL: ${{ vars.AG_GRID_CDN_URL }}
        AG_GRID_TARGET_PATH: ${{ vars.AG_GRID_TARGET_PATH }}
      run: |
        aws s3 sync website/common s3://"$AWS_S3_BUCKET"/common --delete;
        aws s3 sync website/pages s3://"$AWS_S3_BUCKET"/pages --delete;
        aws s3 cp website/index.html s3://"$AWS_S3_BUCKET"/index.html;
        curl "$AG_GRID_CDN_URL" | aws s3 cp - s3://"$AWS_S3_BUCKET"/"$AG_GRID_TARGET_PATH";
