# upload website to s3 bucket

name: uploadToS3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Sync files to S3
      # direct exclude with globing does not work properly, so using enumeration of subdirs
      run: |
        export AWS_ENDPOINT_URL=${{ secrets.AWS_ENDPOINT_URL }};
        export AWS_REGION_NAME=${{ secrets.AWS_REGION_NAME }};
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }};
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }};
        curl ${{ vars.AG_GRID_CDN_URL }} | aws s3 cp - s3://${{ secrets.AWS_S3_BUCKET }}${{ vars.AG_GRID_TARGET_PATH }};
        unset AWS_ACCESS_KEY_ID;
        unset AWS_SECRET_ACCESS_KEY;
