# thanks for https://github.com/enamhasan/GitHub-S3-Sync
# upload website to s3 bucket

name: uploadToS3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION_NAME }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    - name: Sync files to S3
      run: |
        aws s3 sync ./website/index.html s3://${{ secrets.AWS_S3_BUCKET }} \
          --endpoint-url ${{ secrets.AWS_ENDPOINT_URL }} \
          --delete
