# thanks for https://github.com/enamhasan/GitHub-S3-Sync
# upload website to s3 bucket

name: uploadToS3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    - name: Sync files to S3
      run: |
        aws s3 sync website/pages s3://${{ secrets.AWS_S3_BUCKET }}/pages \
          --endpoint-url ${{ secrets.AWS_ENDPOINT_URL }} \
          --region ${{ secrets.AWS_REGION_NAME}} \
          --delete
